[phases.setup]
nixPkgs = ["php", "composer", "yarn"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:clear",
  "php artisan storage:link",
  "php artisan migrate --force"
]

[phases.start]
cmd = "php -S 0.0.0.0:$PORT -t public"
